"""Fix models and add commercial features

Revision ID: 23b3d09c9034
Revises: 
Create Date: 2026-05-03 15:35:15.076120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b3d09c9034'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('max_events', sa.Integer(), nullable=True),
    sa.Column('max_participants_per_event', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.drop_table('session_ratings')
    op.drop_table('waitlist')
    op.drop_table('certificate_templates')
    op.drop_table('networking_connections')
    op.drop_table('backups_log')
    op.drop_table('networking_opt_in')
    op.drop_table('past_events')
    op.drop_table('hotels')
    op.add_column('agenda_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('agenda_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('agenda_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agenda_sessions', 'speaker_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'end_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'hall',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_agenda_sessions_id'), 'agenda_sessions', ['id'], unique=False)
    op.create_foreign_key(None, 'agenda_sessions', 'event_settings', ['event_id'], ['id'])
    op.add_column('attendance', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('attendance', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'check_in'::text"))
    op.alter_column('attendance', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('attendance', 'device_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('attendance', 'entry_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.add_column('event_settings', sa.Column('chargily_api_key', sa.Text(), nullable=True))
    op.add_column('event_settings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_settings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('event_settings', 'event_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'حدث جديد'::text"))
    op.alter_column('event_settings', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('event_settings', 'prefix',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('event_settings', 'frozen_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_settings', 'org_label_1',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'الصفة'::text"))
    op.alter_column('event_settings', 'org_label_2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'الجهة'::text"))
    op.alter_column('event_settings', 'org_label_3',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'القسم'::text"))
    op.alter_column('event_settings', 'org_label_4',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'الموقع/المقعد'::text"))
    op.alter_column('event_settings', 'event_timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_settings', 'app_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Diwan Event'::text"))
    op.alter_column('event_settings', 'app_subtitle',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'منصة تسيير الفعاليات'::text"))
    op.alter_column('event_settings', 'participant_label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'مشارك'::text"))
    op.alter_column('event_settings', 'participant_label_plural',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'مشاركين'::text"))
    op.alter_column('event_settings', 'primary_color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'#D4AF37'::text"))
    op.alter_column('event_settings', 'secondary_color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'#022C22'::text"))
    op.alter_column('event_settings', 'accent_color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'#10B981'::text"))
    op.alter_column('event_settings', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('event_settings', 'payment_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'test'::text"))
    op.alter_column('event_settings', 'welcome_icon',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'fa-star'::text"))
    op.alter_column('event_settings', 'report_signature_1',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'توقيع اللجنة المنظمة'::text"))
    op.alter_column('event_settings', 'report_signature_2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'توقيع المسؤول'::text"))
    op.alter_column('event_settings', 'footer_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Diwan Event Manager'::text"))
    op.create_index(op.f('ix_event_settings_id'), 'event_settings', ['id'], unique=False)
    op.create_foreign_key(None, 'event_settings', 'users', ['created_by'], ['id'])
    op.drop_column('event_settings', 'hotel_map')
    op.drop_column('event_settings', 'doc_link_2')
    op.drop_column('event_settings', 'hotel_price')
    op.drop_column('event_settings', 'doc_link_1')
    op.drop_column('event_settings', 'doc_link_3')
    op.drop_column('event_settings', 'venue_map_url')
    op.drop_column('event_settings', 'hotel_phone')
    op.drop_column('event_settings', 'hotel_name')
    op.drop_column('event_settings', 'venue_map_link')
    op.add_column('participants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('participants', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('participants', 'order_num',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('participants', 'qr_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('participants', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('participants', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('participants', 'council',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('participants', 'court',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('participants', 'seat_info',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('participants', 'id_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('participants', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('participants', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('participants', 'payment_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'paid'::text"))
    op.alter_column('participants', 'entry_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'imported'::text"))
    op.alter_column('participants', 'original_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('participants', 'corrected_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_order_num'), 'participants', ['order_num'], unique=False)
    op.create_index(op.f('ix_participants_qr_code'), 'participants', ['qr_code'], unique=False)
    op.create_foreign_key(None, 'participants', 'event_settings', ['event_id'], ['id'])
    op.add_column('poll_options', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('poll_options', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_poll_options_id'), 'poll_options', ['id'], unique=False)
    op.drop_constraint(op.f('poll_options_poll_id_fkey'), 'poll_options', type_='foreignkey')
    op.create_foreign_key(None, 'poll_options', 'polls', ['poll_id'], ['id'])
    op.add_column('poll_votes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('poll_votes_poll_id_participant_id_key'), 'poll_votes', type_='unique')
    op.create_index(op.f('ix_poll_votes_id'), 'poll_votes', ['id'], unique=False)
    op.drop_constraint(op.f('poll_votes_participant_id_fkey'), 'poll_votes', type_='foreignkey')
    op.drop_constraint(op.f('poll_votes_option_id_fkey'), 'poll_votes', type_='foreignkey')
    op.drop_constraint(op.f('poll_votes_poll_id_fkey'), 'poll_votes', type_='foreignkey')
    op.create_foreign_key(None, 'poll_votes', 'poll_options', ['option_id'], ['id'])
    op.create_foreign_key(None, 'poll_votes', 'polls', ['poll_id'], ['id'])
    op.create_foreign_key(None, 'poll_votes', 'participants', ['participant_id'], ['id'])
    op.add_column('polls', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=False)
    op.drop_constraint(op.f('polls_event_id_fkey'), 'polls', type_='foreignkey')
    op.create_foreign_key(None, 'polls', 'event_settings', ['event_id'], ['id'])
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('questions', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_foreign_key(None, 'questions', 'event_settings', ['event_id'], ['id'])
    op.add_column('social_wall', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('social_wall', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('social_wall', 'author_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('social_wall', 'emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'👏'::text"))
    op.create_index(op.f('ix_social_wall_id'), 'social_wall', ['id'], unique=False)
    op.create_foreign_key(None, 'social_wall', 'event_settings', ['event_id'], ['id'])
    op.add_column('speakers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('speakers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('speakers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('speakers', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speakers', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_speakers_id'), 'speakers', ['id'], unique=False)
    op.create_foreign_key(None, 'speakers', 'event_settings', ['event_id'], ['id'])
    op.add_column('sponsors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('sponsors', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sponsors', 'tier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'gold'::text"))
    op.create_index(op.f('ix_sponsors_id'), 'sponsors', ['id'], unique=False)
    op.create_foreign_key(None, 'sponsors', 'event_settings', ['event_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'admin'::text"))
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'event_credits')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.add_column('wall_likes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('wall_likes', 'session_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('wall_likes_post_id_session_key_key'), 'wall_likes', type_='unique')
    op.create_index(op.f('ix_wall_likes_id'), 'wall_likes', ['id'], unique=False)
    op.drop_constraint(op.f('wall_likes_post_id_fkey'), 'wall_likes', type_='foreignkey')
    op.create_foreign_key(None, 'wall_likes', 'social_wall', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wall_likes', type_='foreignkey')
    op.create_foreign_key(op.f('wall_likes_post_id_fkey'), 'wall_likes', 'social_wall', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_wall_likes_id'), table_name='wall_likes')
    op.create_unique_constraint(op.f('wall_likes_post_id_session_key_key'), 'wall_likes', ['post_id', 'session_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('wall_likes', 'session_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('wall_likes', 'updated_at')
    op.add_column('users', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('event_credits', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'admin'::text"))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'sponsors', type_='foreignkey')
    op.drop_index(op.f('ix_sponsors_id'), table_name='sponsors')
    op.alter_column('sponsors', 'tier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'gold'::text"))
    op.alter_column('sponsors', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('sponsors', 'updated_at')
    op.drop_constraint(None, 'speakers', type_='foreignkey')
    op.drop_index(op.f('ix_speakers_id'), table_name='speakers')
    op.alter_column('speakers', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('speakers', 'updated_at')
    op.drop_column('speakers', 'created_at')
    op.drop_constraint(None, 'social_wall', type_='foreignkey')
    op.drop_index(op.f('ix_social_wall_id'), table_name='social_wall')
    op.alter_column('social_wall', 'emoji',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'👏'::text"))
    op.alter_column('social_wall', 'author_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('social_wall', 'updated_at')
    op.drop_column('social_wall', 'image_url')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.alter_column('questions', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.create_foreign_key(op.f('polls_event_id_fkey'), 'polls', 'event_settings', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.drop_column('polls', 'updated_at')
    op.drop_constraint(None, 'poll_votes', type_='foreignkey')
    op.drop_constraint(None, 'poll_votes', type_='foreignkey')
    op.drop_constraint(None, 'poll_votes', type_='foreignkey')
    op.create_foreign_key(op.f('poll_votes_poll_id_fkey'), 'poll_votes', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('poll_votes_option_id_fkey'), 'poll_votes', 'poll_options', ['option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('poll_votes_participant_id_fkey'), 'poll_votes', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_poll_votes_id'), table_name='poll_votes')
    op.create_unique_constraint(op.f('poll_votes_poll_id_participant_id_key'), 'poll_votes', ['poll_id', 'participant_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('poll_votes', 'updated_at')
    op.drop_constraint(None, 'poll_options', type_='foreignkey')
    op.create_foreign_key(op.f('poll_options_poll_id_fkey'), 'poll_options', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_poll_options_id'), table_name='poll_options')
    op.drop_column('poll_options', 'updated_at')
    op.drop_column('poll_options', 'created_at')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_index(op.f('ix_participants_qr_code'), table_name='participants')
    op.drop_index(op.f('ix_participants_order_num'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.alter_column('participants', 'corrected_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'original_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'entry_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'imported'::text"))
    op.alter_column('participants', 'payment_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'paid'::text"))
    op.alter_column('participants', 'phone_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'id_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'seat_info',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'court',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('participants', 'council',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('participants', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('participants', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('participants', 'qr_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('participants', 'order_num',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('participants', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('participants', 'updated_at')
    op.add_column('event_settings', sa.Column('venue_map_link', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('hotel_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('hotel_phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('venue_map_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('doc_link_3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('doc_link_1', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('hotel_price', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('doc_link_2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('hotel_map', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_settings', type_='foreignkey')
    op.drop_index(op.f('ix_event_settings_id'), table_name='event_settings')
    op.alter_column('event_settings', 'footer_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Diwan Event Manager'::text"))
    op.alter_column('event_settings', 'report_signature_2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'توقيع المسؤول'::text"))
    op.alter_column('event_settings', 'report_signature_1',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'توقيع اللجنة المنظمة'::text"))
    op.alter_column('event_settings', 'welcome_icon',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'fa-star'::text"))
    op.alter_column('event_settings', 'payment_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'test'::text"))
    op.alter_column('event_settings', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('event_settings', 'accent_color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'#10B981'::text"))
    op.alter_column('event_settings', 'secondary_color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'#022C22'::text"))
    op.alter_column('event_settings', 'primary_color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'#D4AF37'::text"))
    op.alter_column('event_settings', 'participant_label_plural',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'مشاركين'::text"))
    op.alter_column('event_settings', 'participant_label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'مشارك'::text"))
    op.alter_column('event_settings', 'app_subtitle',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'منصة تسيير الفعاليات'::text"))
    op.alter_column('event_settings', 'app_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Diwan Event'::text"))
    op.alter_column('event_settings', 'event_timestamp',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_settings', 'org_label_4',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'الموقع/المقعد'::text"))
    op.alter_column('event_settings', 'org_label_3',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'القسم'::text"))
    op.alter_column('event_settings', 'org_label_2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'الجهة'::text"))
    op.alter_column('event_settings', 'org_label_1',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'الصفة'::text"))
    op.alter_column('event_settings', 'frozen_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_settings', 'prefix',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('event_settings', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('event_settings', 'event_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'حدث جديد'::text"))
    op.drop_column('event_settings', 'updated_at')
    op.drop_column('event_settings', 'created_at')
    op.drop_column('event_settings', 'chargily_api_key')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.alter_column('attendance', 'entry_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance', 'device_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'check_in'::text"))
    op.drop_column('attendance', 'updated_at')
    op.drop_column('attendance', 'created_at')
    op.drop_constraint(None, 'agenda_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_agenda_sessions_id'), table_name='agenda_sessions')
    op.alter_column('agenda_sessions', 'hall',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'end_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'start_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'speaker_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agenda_sessions', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('agenda_sessions', 'updated_at')
    op.drop_column('agenda_sessions', 'created_at')
    op.create_table('hotels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('map_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hotels_pkey'))
    )
    op.create_table('past_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_invited', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_present', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attendance_rate', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('db_snapshot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('past_events_pkey'))
    )
    op.create_table('networking_opt_in',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('participant_qr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('networking_opt_in_pkey')),
    sa.UniqueConstraint('event_id', 'participant_qr', name=op.f('networking_opt_in_event_id_participant_qr_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('backups_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backup_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backups_log_pkey'))
    )
    op.create_table('networking_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('requester_qr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requested_qr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('networking_connections_pkey')),
    sa.UniqueConstraint('event_id', 'requester_qr', 'requested_qr', name=op.f('networking_connections_event_id_requester_qr_requested_qr_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('certificate_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bg_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('font_color', sa.TEXT(), server_default=sa.text("'#000000'::text"), autoincrement=False, nullable=True),
    sa.Column('name_y_pos', sa.INTEGER(), server_default=sa.text('400'), autoincrement=False, nullable=True),
    sa.Column('qr_y_pos', sa.INTEGER(), server_default=sa.text('600'), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_settings.id'], name=op.f('certificate_templates_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('certificate_templates_pkey'))
    )
    op.create_table('waitlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('council', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('court', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('promoted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('waitlist_pkey'))
    )
    op.create_table('session_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_ip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('session_ratings_pkey'))
    )
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
