"""add_subscription_plans_and_subscriptions_v6_fix

Revision ID: 2f57f07c76ef
Revises: 62960a7dc5ec
Create Date: 2026-05-08 01:14:57.075645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f57f07c76ef'
down_revision: Union[str, Sequence[str], None] = '62960a7dc5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
