"""professional_networking_v2

Revision ID: 56169754ec5c
Revises: f33e29644c56
Create Date: 2026-05-16 13:09:35.954558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56169754ec5c'
down_revision: Union[str, Sequence[str], None] = 'f33e29644c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networking_connections_id'), table_name='networking_connections')
    op.drop_table('networking_connections')
    op.drop_index(op.f('ix_networking_opt_in_id'), table_name='networking_opt_in')
    op.drop_table('networking_opt_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networking_opt_in',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participant_qr', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_settings.id'], name=op.f('networking_opt_in_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('networking_opt_in_pkey')),
    sa.UniqueConstraint('event_id', 'participant_qr', name=op.f('_optin_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_networking_opt_in_id'), 'networking_opt_in', ['id'], unique=False)
    op.create_table('networking_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requester_qr', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requested_qr', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_settings.id'], name=op.f('networking_connections_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('networking_connections_pkey')),
    sa.UniqueConstraint('event_id', 'requester_qr', 'requested_qr', name=op.f('_networking_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_networking_connections_id'), 'networking_connections', ['id'], unique=False)
    # ### end Alembic commands ###
