"""add_driver_fields_to_committee_task

Revision ID: 63f391ef27b5
Revises: 90de14d4073e
Create Date: 2026-06-07 11:49:20.849770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f391ef27b5'
down_revision: Union[str, Sequence[str], None] = '90de14d4073e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee_tasks', sa.Column('driver_name', sa.String(), nullable=True))
    op.add_column('committee_tasks', sa.Column('driver_phone', sa.String(), nullable=True))
    op.add_column('committee_tasks', sa.Column('driver_vehicle', sa.String(), nullable=True))
    op.add_column('committee_tasks', sa.Column('whatsapp_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee_tasks', 'whatsapp_sent')
    op.drop_column('committee_tasks', 'driver_vehicle')
    op.drop_column('committee_tasks', 'driver_phone')
    op.drop_column('committee_tasks', 'driver_name')
    # ### end Alembic commands ###
