"""add allow_online_payment field

Revision ID: a6c683c69b92
Revises: a8f2e1b9c3d7
Create Date: 2026-07-04 02:17:18.898408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c683c69b92'
down_revision: Union[str, Sequence[str], None] = 'a8f2e1b9c3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_settings', sa.Column('allow_online_payment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_settings', 'allow_online_payment')
    # ### end Alembic commands ###
