"""remove_payment_keys_from_event

Revision ID: ed9c6a342fdd
Revises: 23b3d09c9034
Create Date: 2026-05-04 22:02:05.269698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9c6a342fdd'
down_revision: Union[str, Sequence[str], None] = '23b3d09c9034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('event_settings', sa.Column('payment_gateway', sa.String(), nullable=True))
    op.drop_column('event_settings', 'chargily_api_key')
    op.drop_column('event_settings', 'stripe_secret_key')
    op.add_column('participants', sa.Column('email_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'email_status')
    op.add_column('event_settings', sa.Column('stripe_secret_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_settings', sa.Column('chargily_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('event_settings', 'payment_gateway')
    op.drop_column('agenda_sessions', 'is_active')
    # ### end Alembic commands ###
