"""update_templates_v3

Revision ID: f33e29644c56
Revises: 2f57f07c76ef
Create Date: 2026-05-15 19:57:03.824883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33e29644c56'
down_revision: Union[str, Sequence[str], None] = '2f57f07c76ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_templates_id'), table_name='certificate_templates')
    op.drop_table('certificate_templates')
    op.add_column('badge_templates', sa.Column('type', sa.String(), nullable=True))
    op.add_column('badge_templates', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('badge_templates', sa.Column('design_json', sa.Text(), nullable=True))

    op.execute("UPDATE badge_templates SET type = 'badge'")
    op.execute("UPDATE badge_templates SET created_by = 1")
    op.execute("UPDATE badge_templates SET design_json = '{}'")

    op.alter_column('badge_templates', 'type', nullable=False)
    op.alter_column('badge_templates', 'created_by', nullable=False)
    op.alter_column('badge_templates', 'design_json', nullable=False)
    op.add_column('badge_templates', sa.Column('width_mm', sa.Integer(), nullable=True))
    op.add_column('badge_templates', sa.Column('height_mm', sa.Integer(), nullable=True))
    op.add_column('badge_templates', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('badge_templates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('badge_templates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'badge_templates', 'users', ['created_by'], ['id'])
    op.drop_column('badge_templates', 'elements_config')
    op.drop_column('badge_templates', 'is_active')
    op.drop_column('badge_templates', 'accent_color')
    op.drop_column('badge_templates', 'body_bg')
    op.drop_column('badge_templates', 'header_bg')
    op.drop_column('badge_templates', 'style_preset')
    op.drop_column('badge_templates', 'page_size')
    op.drop_column('badge_templates', 'background_image')
    op.drop_column('badge_templates', 'footer_bg')
    op.create_index(op.f('ix_event_documents_id'), 'event_documents', ['id'], unique=False)
    op.create_index(op.f('ix_wall_comments_id'), 'wall_comments', ['id'], unique=False)
    op.drop_constraint(op.f('wall_comments_post_id_fkey'), 'wall_comments', type_='foreignkey')
    op.create_foreign_key(None, 'wall_comments', 'social_wall', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wall_comments', type_='foreignkey')
    op.create_foreign_key(op.f('wall_comments_post_id_fkey'), 'wall_comments', 'social_wall', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_wall_comments_id'), table_name='wall_comments')
    op.drop_index(op.f('ix_event_documents_id'), table_name='event_documents')
    op.add_column('badge_templates', sa.Column('footer_bg', sa.VARCHAR(), server_default=sa.text("'#F8FAFC'::character varying"), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('background_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('page_size', sa.VARCHAR(), server_default=sa.text("'A6'::character varying"), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('style_preset', sa.VARCHAR(), server_default=sa.text("'modern'::character varying"), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('header_bg', sa.VARCHAR(), server_default=sa.text("'#022C22'::character varying"), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('body_bg', sa.VARCHAR(), server_default=sa.text("'#FFFFFF'::character varying"), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('accent_color', sa.VARCHAR(), server_default=sa.text("'#D4AF37'::character varying"), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('badge_templates', sa.Column('elements_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'badge_templates', type_='foreignkey')
    op.drop_column('badge_templates', 'updated_at')
    op.drop_column('badge_templates', 'created_at')
    op.drop_column('badge_templates', 'is_default')
    op.drop_column('badge_templates', 'height_mm')
    op.drop_column('badge_templates', 'width_mm')
    op.drop_column('badge_templates', 'design_json')
    op.drop_column('badge_templates', 'created_by')
    op.drop_column('badge_templates', 'type')
    op.create_table('certificate_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('background_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('elements_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_settings.id'], name=op.f('certificate_templates_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificate_templates_pkey'))
    )
    op.create_index(op.f('ix_certificate_templates_id'), 'certificate_templates', ['id'], unique=False)
    # ### end Alembic commands ###
